version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: memory_postgres
    environment:
      POSTGRES_DB: memory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  memory_api:
    build: .
    container_name: memory_api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/memory_db
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      ENV: development
    volumes:
      - ./:/app
    command: uvicorn main_v2:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata: